openapi: "3.1.0"
info:
  title: "backend API"
  description: "backend API"
  version: "1.0.0"
servers:
  - url: https://server.com
    description: New server
  - url: "https://backend"
paths:
  /api/v1/products/{id}:
    put:
      summary: "PUT api/v1/products/{id}"
      operationId: "updateProductInform"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductInformRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/products/{id}/prices:
    put:
      summary: "PUT api/v1/products/{id}/prices"
      operationId: "updateProductPrice"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddProductPriceRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
    post:
      summary: "POST api/v1/products/{id}/prices"
      operationId: "createProductPrice"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddProductPriceRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/v1/products:
    post:
      summary: "POST api/v1/products"
      operationId: "createProduct"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/products/{id}/prices/{sizeId}:
    delete:
      summary: "DELETE api/v1/products/{id}/prices/{sizeId}"
      operationId: "deleteProductPrice"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
        - name: "sizeId"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
  /api/v1/categories/{id}:
    put:
      summary: "PUT api/v1/categories/{id}"
      operationId: "updateCategory"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/categories:
    post:
      summary: "POST api/v1/categories"
      operationId: "createCategory"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategoryRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/units/{id}:
    put:
      summary: "PUT api/v1/units/{id}"
      operationId: "updateUnit"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUnitRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/units:
    post:
      summary: "POST api/v1/units"
      operationId: "createUnit"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUnitRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/product-sizes/{id}:
    put:
      summary: "PUT api/v1/product-sizes/{id}"
      operationId: "updateProductSize"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductSizeRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
  /api/v1/product-sizes:
    post:
      summary: "POST api/v1/product-sizes"
      operationId: "createProductSize"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductSizeRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "integer"
                format: "int32"
components:
  schemas:
    UpdateProductInformRequest:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        categoryId:
          type: "integer"
          format: "int32"
    BigDecimal:
      type: "object"
      properties: { }
    ProductPriceRequest:
      type: "object"
      properties:
        sizeId:
          type: "integer"
          format: "int32"
        price:
          $ref: "#/components/schemas/BigDecimal"
    AddProductPriceRequest:
      type: "object"
      properties:
        productPrices:
          $ref: "#/components/schemas/ProductPriceRequest"
    CreateProductRequest:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        categoryId:
          type: "integer"
          format: "int32"
        available:
          type: "boolean"
        signature:
          type: "boolean"
        imagePath:
          type: "string"
        prices:
          type: "integer"
          format: "int32"
    CreateCategoryRequest:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
        parentId:
          type: "integer"
          format: "int32"
    UpdateUnitRequest:
      type: "object"
      properties:
        name:
          type: "string"
        symbol:
          type: "string"
        description:
          type: "string"
    CreateUnitRequest:
      type: "object"
      properties:
        name:
          type: "string"
        symbol:
          type: "string"
        description:
          type: "string"
    UpdateProductSizeRequest:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        unitId:
          type: "integer"
          format: "int32"
        name:
          type: "string"
        description:
          type: "string"
        quantity:
          type: "integer"
          format: "int32"
    CreateProductSizeRequest:
      type: "object"
      properties:
        name:
          type: "string"
        unitId:
          type: "integer"
          format: "int32"
        description:
          type: "string"
        quantity:
          type: "integer"
          format: "int32"