# Common Configuration for All Environments
spring:
  application:
    name: mts-backend-application
  profiles:
    active: dev  # Default profile

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /api-docs/swagger-config
    urls:
      - url: /api-docs
        name: API
    display-request-duration: true
    default-model-expand-depth: 1
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# JWT Configuration (Common)
jwt-config:
  secret: hdvfkfvewfowefihpqhfphwgbwiegihgwinwgnwigiwgiweigoewog
  expiration: 100000 #1000000
  header: Authorization
  prefix: Bearer
  token-type: JWT
  issuer: mts-backend

# Firebase Configuration (Common)
firebase-config:
  bucket: ${FIREBASE_BUCKET_NAME}

---
# Development Environment Profile
spring:
  config:
    activate:
      on-profile: dev

  security:
    user:
      name: user
      password: user

  datasource:
    url: jdbc:mysql://proxysql:6033/milk_tea_shop_prod?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: proxyuser
    password: proxyuser
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: milk_tea_shop_prod
        connection:
          driver_class: com.mysql.cj.jdbc.Driver
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  flyway:
    enabled: false # Disable Flyway in dev, enable in prod

server:
  port: 8181

springdoc: # SpringDoc specific to dev (if any, otherwise can be removed if identical to common)
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.myapp: DEBUG
    org.hibernate: DEBUG
    org.springframework.security: DEBUG

---
# Production Environment Profile
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:mysql://proxysql:6033/${DB_NAME}?logger=com.mysql.cj.log.Slf4JLogger&profileSQL=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 9090

springdoc: # SpringDoc specific to prod
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    root: WARN
    org.springframework: ERROR
    com.myapp: WARN
  file:
    name: /var/log/myapp/application.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Cache configuration for production (placeholder if any)
# Example:
# spring:
#   cache:
#     type: redis
#     redis:
#       host: localhost
#       port: 6379

# Database configuration (comments - actual config is under datasource)
# Logging configuration (comments - actual config is under logging)

